//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : administrator.java
//  @ Date : 05/11/2017
//  @ Author : 
//
//




public class administrator
{
    private string name;
    private int id;
    private string pass;
    public void add function()
    {
    
    }
}
