//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Blind person.java
//  @ Date : 05/11/2017
//  @ Author : 
//
//




public class Blind person
{
    protected string name;
    public void request()
    {
    
    }
    
    public void learn()
    {
    
    }
}
