//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Function database.java
//  @ Date : 05/11/2017
//  @ Author : 
//
//




public class Function database extends alphabets, alphabets, tables, numeric, music
{
    public string function title;
    public void update()
    {
    
    }
}
